version: 2

project_name: wg-tray-go

before:
  hooks:
    - go mod tidy

builds:
  - &build_base
    id: linux-amd64
    main: .
    binary: wg-tray-go
    goos: [linux]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

  - <<: *build_base
    id: linux-arm64
    goarch: [arm64]
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc

  - <<: *build_base
    id: darwin-amd64
    goos: [darwin]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
      - CC=o64-clang

  - <<: *build_base
    id: darwin-arm64
    goos: [darwin]
    goarch: [arm64]
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang

archives:
  - id: default
    formats: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - linux-amd64
      - linux-arm64
      - darwin-amd64
      - darwin-arm64

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: github
