name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      # The base64 of the contents of your '.p12' key.
      MACOS_SIGN_P12: ${{ secrets.APPLE_CERT_P12 }}

      # The password to open the '.p12' key.
      MACOS_SIGN_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}

      # A password for our temporary keychain
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

      # The base64 of the contents of your '.p8' key.
      MACOS_NOTARY_KEY: ${{ secrets.APPLE_NOTARY_KEY }}

      # The ID of the '.p8' key.
      # You can find it in the filename, as well as the Apple Developer Portal
      # website.
      MACOS_NOTARY_KEY_ID: ${{ secrets.APPLE_NOTARY_KEY_ID }}

      # The issuer UUID.
      # You can find it in the Apple Developer Portal website.
      MACOS_NOTARY_ISSUER_ID: ${{ secrets.APPLE_NOTARY_ISSUER_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y libayatana-appindicator3-dev pkg-config

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      # # Needed for macOS signing/notarization in GoReleaser
      # - name: Import Apple certificate
      #   if: startsWith(matrix.id, 'darwin-')
      #   env:
      #     APPLE_CERT_P12: ${{ secrets.APPLE_CERT_P12 }}
      #     APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
      #     KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      #   run: |
      #     set -euo pipefail
      #     KEYCHAIN=build.keychain
      #     KEYCHAIN_PASSWORD="$(openssl rand -base64 24)"
      #     echo "$APPLE_CERT_P12" | base64 --decode > /tmp/cert.p12

      #     security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN"
      #     security set-keychain-settings -lut 21600 "$KEYCHAIN"
      #     security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN"
      #     security import /tmp/cert.p12 -k "$KEYCHAIN" -P "$APPLE_CERT_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security
      #     security list-keychains -d user -s "$KEYCHAIN" login.keychain-db
      #     security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN"

      - name: Run GoReleaser (split by target)
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean
